server:
  port: 0
spring:
  application:
    name: ai-sentiment-processor
  cloud:
    function:
      definition: embeddingSimilarityFunction
    stream:
      function:
        bindings:
          embeddingSimilarityFunction-in-0: input
          embeddingSimilarityFunction-out-0: output
      binder:
        connection-name-prefix: ${spring.application.name}
      bindings:
        input:
          group: ai-sentiment-processor
  ai:
    ollama:
      base-url: http://localhost:11434
      model: llama3
      init:
        pull-model-strategy: always
        timeout: 60s
        max-retries: 1
    #
  jpa:
    show-sql: true
logging:
  level:
    org:
      springframework:
        ai: debug